{% set name = "aws-session-manager-plugin" %}
{% set version = "1.2.339.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name.replace("-", "/", 1) }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c9468b8c5f671e82cf353f748fc4996f1244722bb76c85c1e6661179b4bbf06
  patches:
    - windows-makefile-1.2.312.0.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }} 1.15
    # 1.1.0 requires aws/session-manager-plugin to use git modules
    - go-licenses >=0.0.44,<1.1.0
    - make
    # Makefile uses some unix shell utilities
    - m2-base  # [win]
    - m2-patch  # [win]

  run:
    - awscli

test:
  commands:
    - session-manager-plugin --version
    - ssmcli help

about:
  home: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - license-files/
  summary: AWS Command Line Interface plugin to start and end sessions
  description: |
    Session Manager is a fully managed AWS Systems Manager capability that
    lets you manage your Amazon Elastic Compute Cloud (Amazon EC2) instances,
    on-premises instances and virtual machines. Session Manager provides
    secure and auditable instance management without the need to open inbound
    ports. When you use the Session Manager plugin with the AWS CLI to start a
    session, the plugin builds the websocket connection to your managed
    instances.
  dev_url: https://github.com/aws/session-manager-plugin
  doc_url: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html

extra:
  recipe-maintainers:
    - manics
